Sonata\MediaBundle\Model\Media:
  exclusion_policy: all
  properties:
    enabled:
      expose: true
      groups: ['list','details','json.qr.find','json.session.read']
    name:
      expose: true
      groups: ['list','details','json.qr.find','json.session.read']
    contentType:
      expose: true
      groups: ['list','details','json.qr.find','json.session.read']