Sonata\MediaBundle\Model\Gallery:
  exclusion_policy: all
  properties:
    enabled:
      expose: true
      groups: ['json']
    name:
      expose: true
      groups: ['json']
    galleryHasMedias:
      expose: true
      groups: ['json']
      