Sonata\MediaBundle\Model\Media:
  exclusion_policy: all
  properties:
    enabled:
      expose: true
      groups: ['list','details','json']
    name:
      expose: true
      groups: ['list','details','json']
    contentType:
      expose: true
      groups: ['list','details','json']
    providerReference:
      expose: true
      groups: ['list','details','json']
