Sonata\MediaBundle\Model\GalleryHasMedia:
  exclusion_policy: all
  properties:
    enabled:
      expose: true
      groups: ['json']
    position:
      expose: true
      groups: ['json']
    media:
      expose: true
      groups: ['json']
      