sonata_admin:
    title:      "Youppers Admin"
    title_logo: 'bundles/youpperscommon/logo_35x40.png'
    
    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        #layout:  SonataAdminBundle::standard_layout.html.twig
        layout: YouppersCommonBundle:Admin:layout.html.twig
        short_object_description: YouppersCommonBundle:Helper:short-object-description.html.twig
        select:               'YouppersCommonBundle:CRUD:list__select.html.twig'

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list } # default
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
#            - { position: right, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Welcome!</h3></div><div class='panel-body'>You can customize this dashboard by editing the <code>sonata_admin.yml</code> file. The current dashboard presents the recent items from the NewsBundle and a non-statistical e-commerce information.</div></div>"} }                          
            # This block is disabled for now as the bundle generates an exception with composite key
#            - { position: left, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25 }}

#            - { position: left, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
#            - { position: left, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 7, mode: admin }}
#            - { position: right, type: sonata.order.block.recent_orders, settings: { title: Recent Orders, number: 5, mode: admin }}
#            - { position: right, type: sonata.customer.block.recent_customers, settings: { title: Recent Customers, number: 5, mode: admin }}
#            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss, template: SonataAdminBundle:Block:block_rss_dashboard.html.twig }}

#        groups:
#            sonata.admin.group.company:
#                label:  Company
#                #label_catalogue: YouppersCompanyBundle
#                icon:  '<i class="fa fa-building fa-fw"></i>'
#                items:
#                    - youppers.company.admin.company
#                    - youppers.company.admin.brand
#                    - youppers.company.admin.product
#                    - sonata.product.admin.product
#                item_adds: []
#                roles: [ROLE_COMPANY]
                    
                    
            
#            sonata.admin.group.content:
#                label:           sonata_content
#                label_catalogue: SonataDemoBundle
#                icon:            '<i class="fa fa-th"></i>'
#                items:
#                    - sonata.news.admin.comment
#                    - sonata.news.admin.post
#                    - sonata.media.admin.media
#                    - sonata.media.admin.gallery
#                    - sonata.comment.admin.thread
#
#            sonata.admin.group.ecommerce:
#                label:           sonata_ecommerce
#                label_catalogue: SonataAdminBundle
#                icon:            '<i class="fa fa-dollar"></i>'
#                items:
#                    - sonata.customer.admin.customer
#                    - sonata.invoice.admin.invoice
#                    - sonata.order.admin.order
#                    - sonata.product.admin.product
#
#            sonata.admin.group.classification:
#                label:           sonata_classification
#                label_catalogue: SonataClassificationBundle
#                icon:            '<i class="fa fa-sitemap"></i>'
#                items:
#                    - sonata.classification.admin.category
#                    - sonata.classification.admin.tag
#                    - sonata.classification.admin.collection
#
#            sonata.admin.group.site_builder:
#                label:           Site Builder
#                label_catalogue: SonataDemoBundle
#                icon:            '<i class="fa fa-puzzle-piece"></i>'
#                items:
#                    - sonata.page.admin.page
#                    - sonata.page.admin.site
#
#            sonata.admin.group.administration:
#                label:           sonata_administration
#                label_catalogue: SonataAdminBundle
#                icon:            '<i class="fa fa-cogs"></i>'
#                items:
#                    - sonata.user.admin.user
#                    - sonata.user.admin.group
#                    - sonata.page.admin.site
#                    - sonata.notification.admin.message
#
#            sonata.admin.group.demo:
#                label: Demo
#                icon:  '<i class="fa fa-play-circle"></i>'
#                items:
#                    - sonata.demo.admin.car
#                    - sonata.demo.admin.engine
#                    - sonata.demo.admin.color
#                    - sonata.demo.admin.material

    persist_filters: true