sonata_product:
    products:
            
#        # Goodies
#        sonata.ecommerce_demo.product.goodie:
#            provider: sonata.ecommerce_demo.product.goodie.type
#            manager:  sonata.ecommerce_demo.product.goodie.manager
#
#        # Travel
#        sonata.ecommerce_demo.product.travel:
#            provider: sonata.ecommerce_demo.product.travel.type
#            manager: sonata.ecommerce_demo.product.travel.manager
#            variations:
#                fields: [travellers, travelDays, sku, slug, name, price, stock, vatRate, priceIncludingVat, enabled]
#
        youppers.company.product.generic:
            provider: youppers.company.product.generic.type
            manager: youppers.company.product.generic.manager            

        youppers.company.product.tile:
            provider: youppers.company.product.tile.type
            manager: youppers.company.product.tile.manager
            variations:
              fields: [size]

    seo:
        product:
            site: '@youppers'
            creator: '@youppers'
            domain: 'http://www.youppers.com'
            media_prefix: 'http://www.youppers.com'
            media_format: 'reference'



# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataProductBundle: ~
                    SonataProductBundle: ~