sonata_admin:
    title:      "Youppers Admin"
    title_logo: 'bundles/youpperscommon/logo_35x40.png'
    templates:
        layout: YouppersCommonBundle:Admin:standard_layout.html.twig
        short_object_description: YouppersCommonBundle:Admin:short-object-description.html.twig
        