fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main

    # if you change the class configuration, please also alter the sonata_user.yml file
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: "youppers-users@youppers.com"
        sender_name: "Youppers (demo)"

    registration:
        confirmation:
            enabled:              true
            template:             'FOSUserBundle:Registration:email.txt.twig'
            from_email:
                address:              "youppers-registration-confirmation@youppers.com"
                sender_name:          "Youppers (demo)"
