services:
    youppers_common.admin.geoid:
        class: Youppers\CommonBundle\Admin\GeoidAdmin
        arguments: [~, Youppers\CommonBundle\Entity\Geoid, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Common, label: 'Geoid'}

    youppers_common.admin.qr:
        class: Youppers\CommonBundle\Admin\QrAdmin
        arguments: [~, Youppers\CommonBundle\Entity\Qr, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Common, label: 'QRCode'}

    youppers.common.admin.org:
        class: Youppers\CommonBundle\Admin\OrgAdmin
        arguments: [~, Youppers\CommonBundle\Entity\Org, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Common, label: 'Organization'}
