youppers_common:
  qr: 
    youppers_dealer_box:
      entity: 'Youppers\DealerBundle\Entity\Box'
      route: youppers_dealer_box_show 
      
    youppers_company_product:
      entity: 'Youppers\CompanyBundle\Entity\Product'
      route: youppers_company_product_show
