wa72_json_rpc:
    functions:
        qrFind:
            service: "youppers.common.qr"
            method: "find"
            jms_serialization_context:
                groups:
                  - json
                version: "1"
                max_depth_checks: true
