wa72_json_rpc:
    functions:
        qrFind:
            service: "youppers.common.qr"
            method: "find"
            jms_serialization_context:
                groups:
                  - json
                version: "1"
                max_depth_checks: true

        newSession: { service: youppers_customer.controller.session, method: newSession, jms_serialization_context: { groups: [json, create], version: '1', max_depth_checks: true } }
        qrScan: { service: youppers.common.qr, method: scan, jms_serialization_context: { groups: [json], version: '1', max_depth_checks: true } }
