wa72_json_rpc:
    functions:
        #deprecated
        qrFind:
            service: "youppers.common.qr"
            method: "find"
            jms_serialization_context:
                groups:
                  - json
                  - json.qr.find
                version: "1"
                max_depth_checks: true
        #deprecated
        newSession: { service: youppers_customer.controller.session, method: newSession, jms_serialization_context: { groups: [json, create], version: '1', max_depth_checks: true } }

        Session.new: { service: youppers_customer.controller.session, method: newSession, jms_serialization_context: { groups: [json, create], version: '1', max_depth_checks: true } }
        Qr.find: { service: youppers.common.qr, method: find, jms_serialization_context: { groups: [json.qr.find], version: '1', max_depth_checks: true } }
