services:
  happyr.google.analytics.clientIdProvider:
    class: 'Youppers\CommonBundle\Analytics\ClientIdProvider'
    calls:
          - [setRequest, ['@?request=']]
          
  happyr.google.analytics.http.client:
    class: 'Youppers\CommonBundle\Analytics\HttpClient'
    arguments:
      - '%happyr.google.analytics.param.endpoint%'
      - '%happyr.google.analytics.param.fireAndForget%'
      - '%happyr.google.analytics.param.requestTimeout%'
    calls:
          - [setRequest, ['@?request=']]
          - [setLogger, ['@logger']]

    youppers.locale_listener:
        class: Youppers\CommonBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
            
    youppers.user.login:
        class: Youppers\CommonBundle\EventListener\LoginListener
        arguments: ["@security.context", "@router"]
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: handle }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }            
 
  youppers.common.qr:
      class: 'Youppers\CommonBundle\Qr\QrService'
      arguments: ['@session', '@doctrine.orm.entity_manager' ]

  youppers.common.serialization_listener:
      class: Youppers\CommonBundle\EventListener\SerializationListener
      tags:
          - { name: jms_serializer.event_subscriber }
      