<?php
/*
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Entity;

/**
 * This file has been generated by the Sonata product generation command ( http://sonata-project.org/ )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Tile extends Generic
{
	/**
	 * @var string
	 */
	protected $size;
	
	/**
	 * @param string $size
	 */
	public function setSize($size)
	{
		$this->size = $size;
	}
	
	/**
	 * @return string
	 */
	public function getSize()
	{
		return $this->size;
	}
	
	const SIZE_TSP = 'Small (Tea spoon)';
	const SIZE_S = 'Medium (Spoon)';
	const SIZE_TBSP = 'Large (Tablespoon)';
	
	/**
	 * @return array
	 */
	public static function getSizeList()
	{
		return array(
				static::SIZE_TSP => static::SIZE_TSP,
				static::SIZE_S => static::SIZE_S,
				static::SIZE_TBSP => static::SIZE_TBSP,
		);
	}
}
