services:
    youppers.dealer.consultant:
        class:     Youppers\DealerBundle\Service\ConsultantService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.dealer.service.box:
        class:     Youppers\DealerBundle\Service\BoxService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.dealer.manager.box:
        class:     Youppers\DealerBundle\Manager\BoxManager
        arguments: ['@doctrine']
