# products definition
# generate with:
# php app/console sonata:product:generate
services:
    youppers.company.product.generic.manager:
        class: Sonata\ProductBundle\Entity\ProductManager
        arguments:
            - Application\Sonata\ProductBundle\Entity\Generic
            - '@doctrine'

    youppers.company.product.generic.type:
        class: Application\Sonata\ProductBundle\Provider\GenericProductProvider
        arguments:
            - '@serializer'

    youppers.company.product.tile.manager:
        class: Sonata\ProductBundle\Entity\ProductManager
        arguments:
            - Application\Sonata\ProductBundle\Entity\Tile
            - '@doctrine'

    youppers.company.product.tile.type:
        class: Application\Sonata\ProductBundle\Provider\TileProductProvider
        arguments:
            - '@serializer'
            