services:
    youppers.company.scraper.factory:
        class: 'Youppers\CompanyBundle\Scraper\ScraperFactory'
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.company.pricelist.loader_factory:
        class:     Youppers\CompanyBundle\Loader\PricelistLoaderFactory
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.company.loader.product_loader_factory:
        class:     Youppers\CompanyBundle\Loader\ProductLoaderFactory
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]

#    youppers.company.pricelist.loader.IS:
#        class:     Youppers\CompanyBundle\Service\BasePricelistLoader
#        arguments: ['@doctrine', '@logger']
#        calls:
#            - [ setContainer, [ '@service_container' ] ]
    
    youppers.company.security.company_voter:
        class:     Youppers\CompanyBundle\Security\CompanyVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

    youppers.company.security.brand_voter:
        class:     Youppers\CompanyBundle\Security\BrandVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

    youppers.company.security.product_voter:
        class:     Youppers\CompanyBundle\Security\ProductVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

    youppers.company.security.pricelist_voter:
        class:     Youppers\CompanyBundle\Security\PricelistVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

    youppers.company.security.productprice_voter:
        class:     Youppers\CompanyBundle\Security\ProductPriceVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

    youppers.company.manager.company:
        class:     Youppers\CompanyBundle\Manager\CompanyManager
        arguments: ['Youppers\CompanyBundle\Entity\Company', '@doctrine']

    youppers.company.manager.brand:
        class:     Youppers\CompanyBundle\Manager\BrandManager
        arguments: ['Youppers\CompanyBundle\Entity\Brand','@doctrine']

    youppers.company.manager.product:
        class:     Youppers\CompanyBundle\Manager\ProductManager
        arguments: ['Youppers\CompanyBundle\Entity\Product','@doctrine']
