services:
    youppers_product.admin.product_type:
        class: Youppers\ProductBundle\Admin\ProductTypeAdmin
        arguments: [~, Youppers\ProductBundle\Entity\ProductType,  ~ ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Product Type'}

    youppers_product.admin.product_attribute:
        class: Youppers\ProductBundle\Admin\ProductAttributeAdmin
        arguments: [~, Youppers\ProductBundle\Entity\ProductAttribute, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Product Attribute',  show_in_dashboard: false}

    youppers_product.admin.attribute_type:
        class: Youppers\ProductBundle\Admin\AttributeTypeAdmin
        arguments: [~, Youppers\ProductBundle\Entity\AttributeType,  ~ ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Attribute Type'}
        calls:
            - [addChild, ['@youppers_product.admin.attribute_standard']]

    youppers_product.admin.attribute_standard:
        class: Youppers\ProductBundle\Admin\AttributeStandardAdmin
        arguments: [~, Youppers\ProductBundle\Entity\AttributeStandard, ~ ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Attribute Standard'}

    youppers_product.admin.attribute_option:
        class: Youppers\ProductBundle\Admin\AttributeOptionAdmin
        arguments: [~, Youppers\ProductBundle\Entity\AttributeOption, ~ ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Attribute Option', show_in_dashboard: false}

    youppers_product.admin.product_collection:
        class: Youppers\ProductBundle\Admin\ProductCollectionAdmin
        arguments: [~, Youppers\ProductBundle\Entity\ProductCollection, ~ ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Product Collection'}
        calls:
            - [addChild, ['@youppers_product.admin.product_variant']]

    youppers_product.admin.product_variant:
        class: Youppers\ProductBundle\Admin\ProductVariantAdmin
        arguments: [~, Youppers\ProductBundle\Entity\ProductVariant, "YouppersProductBundle:ProductVariantCRUD" ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Product Variant'}

    youppers_product.admin.variant_property:
        class: Youppers\ProductBundle\Admin\VariantPropertyAdmin
        arguments: [~, Youppers\ProductBundle\Entity\VariantProperty, ~ ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Product, label: 'Variant Property', show_in_dashboard: false}
            