services:
    youppers.product.service.product:
        class:     Youppers\ProductBundle\Service\ProductService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    youppers.product.variant.guesser_factory:
        class:     Youppers\ProductBundle\Guesser\GuesserLoaderFactory
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    youppers.product.manager.product_variant:
        class:     Youppers\ProductBundle\Manager\ProductVariantManager
        arguments: ['@doctrine']

    youppers.product.manager.product_collection:
        class:     Youppers\ProductBundle\Manager\ProductCollectionManager
        arguments: ['@doctrine']

    youppers.product.manager.attribute_option:
        class:     Youppers\ProductBundle\Manager\AttributeOptionManager
        arguments: ['@doctrine']

    youppers.product.security.product_collection_voter:
        class:     Youppers\ProductBundle\Security\ProductCollectionVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

    youppers.product.security.product_variant_voter:
        class:     Youppers\ProductBundle\Security\ProductVariantVoter
        arguments: ['@doctrine', '@logger']
        public:    false
        tags:
            - { name: security.voter }

