services:
    youppers.product.service.product:
        class:     Youppers\ProductBundle\Service\ProductService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    youppers.product.variant.guesser_factory:
        class:     Youppers\ProductBundle\Guesser\GuesserLoaderFactory
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    youppers.product.manager.product_variant:
        class:     Youppers\ProductBundle\Manager\ProductVariantManager
        arguments: ['@doctrine']

    youppers.product.manager.product_collection:
        class:     Youppers\ProductBundle\Manager\ProductCollectionManager
        arguments: ['@doctrine']

    youppers.product.manager.attribute_option:
        class:     Youppers\ProductBundle\Manager\AttributeOptionManager
        arguments: ['@doctrine']
