<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Youppers\CommonBundle\Entity\Org;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    protected $id;

    protected $org;

    /**
     * Get id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set org
     *
     * @param \Youppers\CommonBundle\Entity\Org $org
     *
     * @return User
     */
    public function setOrg(\Youppers\CommonBundle\Entity\Org $org = null)
    {
        $this->org = $org;

        return $this;
    }

    /**
     * Get org
     *
     * @return \Youppers\CommonBundle\Entity\Org
     */
    public function getOrg()
    {
        return $this->org;
    }

}