<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var string $Hashkey
     */
    protected $hashkey;

    /**
     * @var 'Youppers\CommonBundle\Entity\Qr' $qr
     */
    protected $qr;

    /**
     * Get Hashkey
     *
     * @return string $Hashkey
     */
    public function getHashkey()
    {
        return $this->hashkey;
    }

    /**
     * Set Hashkey
     *
     * @return string $Hashkey
     */
    public function setHashkey($Hashkey)
    {
        $this->hashkey = $Hashkey;
        return $this;
    }

    /**
     * Set qr
     *
     * @param \Youppers\CommonBundle\Entity\Qr $qr
     * @return Product
     */
    public function setQr(\Youppers\CommonBundle\Entity\Qr $qr = null)
    {
        $this->qr = $qr;

        return $this;
    }

    /**
     * Get qr
     *
     * @return \Youppers\CommonBundle\Entity\Qr
     */
    public function getQr()
    {
        return $this->qr;
    }

}
