services:
    youppers_customer.controller.session:
        class:     Youppers\CustomerBundle\Controller\SessionController
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.customer.session:
        class:     Youppers\CustomerBundle\Service\SessionService
        arguments: ['@doctrine', '@logger']
            