services:
    youppers_customer.controller.session:
        class:     Youppers\CustomerBundle\Controller\SessionController
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.customer.session:
        class:     Youppers\CustomerBundle\Service\SessionService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    youppers.customer.session.form:    
        class: 'Sonata\CoreBundle\Form\Type\DoctrineORMSerializationType'
        arguments: ['@jms_serializer.metadata_factory', '@doctrine', 'youppers_customer_session_form', 'Youppers\CustomerBundle\Entity\Session','details']
        tags:
           - { name: form.type, alias: youppers_customer_session_form }

    youppers.customer.zone:
        class:     Youppers\CustomerBundle\Service\ZoneService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    