services:
    youppers.customer.service.profile:
        class:     Youppers\CustomerBundle\Service\ProfileService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            - [ setTokenStorage, [ '@security.token_storage' ] ]

    youppers.customer.profile:
      alias: youppers.customer.service.profile
      
    youppers.customer.profile.form:    
        class: 'Sonata\CoreBundle\Form\Type\DoctrineORMSerializationType'
        arguments: ['@jms_serializer.metadata_factory', '@doctrine', 'youppers_customer_profile_form', 'Youppers\CustomerBundle\Entity\Profile','details']
        tags:
           - { name: form.type, alias: youppers_customer_profile_form }

    youppers_customer.controller.session:
        class:     Youppers\CustomerBundle\Controller\SessionController
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.customer.manager.session:
        class:     Youppers\CustomerBundle\Manager\SessionManager
        arguments: ['@doctrine']

    youppers.customer.service.session:
        class:     Youppers\CustomerBundle\Service\SessionService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            - [ setTokenStorage, [ '@security.token_storage' ] ]

    youppers.customer.session:
      alias: youppers.customer.service.session

    youppers.customer.session.form:    
        class: 'Sonata\CoreBundle\Form\Type\DoctrineORMSerializationType'
        arguments: ['@jms_serializer.metadata_factory', '@doctrine', 'youppers_customer_session_form', 'Youppers\CustomerBundle\Entity\Session','details']
        tags:
           - { name: form.type, alias: youppers_customer_session_form }

    youppers.customer.service.zone:
        class:     Youppers\CustomerBundle\Service\ZoneService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            - [ setTokenStorage, [ '@security.token_storage' ] ]

    # @deprecated
    youppers.customer.zone:
      alias: youppers.customer.service.zone

    youppers.customer.zone.form:    
        class: 'Sonata\CoreBundle\Form\Type\DoctrineORMSerializationType'
        arguments: ['@jms_serializer.metadata_factory', '@doctrine', 'youppers_customer_zone_form', 'Youppers\CustomerBundle\Entity\Zone','details']
        tags:
           - { name: form.type, alias: youppers_customer_zone_form }
    
    youppers.customer.manager.item:
        class:     Youppers\CustomerBundle\Manager\ItemManager
        arguments: ['@doctrine']

    youppers.customer.service.item:
        class:     Youppers\CustomerBundle\Service\ItemService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]    
            
    youppers.customer.service.history:
        class:     Youppers\CustomerBundle\Service\HistoryService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    youppers.customer.security.phone_email:
        class:     Youppers\CustomerBundle\Security\PhoneEmailUserProvider
        arguments: ['@fos_user.user_manager']
        
    youppers.customer.manager.history:
        class:     Youppers\CustomerBundle\Manager\HistoryManager
        arguments: ['@doctrine']
