services:
    youppers_customer.controller.session:
        class:     Youppers\CustomerBundle\Controller\SessionController
        calls:
            - [ setContainer, [ '@service_container' ] ]

    youppers.customer.session:
        class:     Youppers\CustomerBundle\Service\SessionService
        arguments: ['@doctrine', '@logger']
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    youppers.customer.session.form:    
        class: 'Sonata\CoreBundle\Form\Type\DoctrineORMSerializationType'
        tag:
           - { form.type: youppers_customer_session_form }
        arguments: ['@jms_serializer.metadata_factory', '@doctrine', 'youppers_customer_session_form', 'Youppers\Customer\Entity\Session']
    