imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

doctrine:
    orm:
        metadata_cache_driver:
            type: memcache
            port: %memcache_port%
        result_cache_driver:
            type: memcache
            port: %memcache_port%
        query_cache_driver:
            type: memcache
            port: %memcache_port%

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
