wa72_json_rpc:
    functions:
        #deprecated use Qr.find
        qrFind:
            service: "youppers.common.qr"
            method: "find"
            jms_serialization_context:
                groups:
                  - json
                  - json.qr.find
                version: "1"
                max_depth_checks: true
        #deprecated use Session.new
        newSession: { service: youppers_customer.controller.session, method: newSession, jms_serialization_context: { groups: [json, create], version: '1', max_depth_checks: true } }

        Session.new: { service: youppers.customer.session, method: newSession, jms_serialization_context: { groups: [json, create], version: '1', max_depth_checks: true } }

        Qr.find: { service: youppers.common.qr, method: find, jms_serialization_context: { groups: [json, json.qr.find], version: '1', max_depth_checks: true } }

        Session.list: { service: youppers.customer.session, method: listForProfile, jms_serialization_context: { groups: [json, json.session.list], version: '1', max_depth_checks: true } }
        Session.create: { service: youppers.customer.session, method: create, jms_serialization_context: { groups: [json, json.session.read], version: '1', max_depth_checks: true } }

        # Read session with details about store, consultant, store and profile
        Session.read: { service: youppers.customer.session, method: read, jms_serialization_context: { groups: [json, json.session.read], version: '1', max_depth_checks: true } }

        # Update session (use Form)
        Session.update: { service: youppers.customer.session, method: update, jms_serialization_context: { groups: [json, json.session.read], version: '1', max_depth_checks: true } }
        
        # List consultant available for the session (Store must be already set in the Session)
        Consultant.list: { service: youppers.dealer.consultant, method: listForSession, jms_serialization_context: { groups: [json, json.consultant.list], version: '1', max_depth_checks: true } }
         
        Product.search: { service: youppers.product.service.product, method: searchProducts, jms_serialization_context: { groups: [json, json.product.list], version: '1', max_depth_checks: true } }
        Variant.list: { service: youppers.product.service.product, method: listVariants, jms_serialization_context: { groups: [json, json.variant.list], version: '1', max_depth_checks: true } }
        Variant.read: { service: youppers.product.service.product, method: readVariant, jms_serialization_context: { groups: [json, json.variant.read], version: '1', max_depth_checks: true } }
        Collection.read: { service: youppers.product.service.product, method: readCollection, jms_serialization_context: { groups: [json, json.collection.read], version: '1', max_depth_checks: true } }
        Attributes.read: { service: youppers.product.service.product, method: readCollectionAttributes, jms_serialization_context: { groups: [json, json.attributes.read], version: '1', max_depth_checks: true } }

        Zone.list: { service: youppers.customer.zone, method: listForSession, jms_serialization_context: { groups: [json, json.zone.list], version: '1', max_depth_checks: true } }
        Zone.create: { service: youppers.customer.zone, method: create, jms_serialization_context: { groups: [json, json.zone.read], version: '1', max_depth_checks: true } }

        Item.list: { service: youppers.customer.item, method: listForSession, jms_serialization_context: { groups: [json, json.item.list], version: '1', max_depth_checks: true } }
        Item.create: { service: youppers.customer.item, method: create, jms_serialization_context: { groups: [json, json.item.read], version: '1', max_depth_checks: true } }
        Item.delete: { service: youppers.customer.item, method: create, jms_serialization_context: { groups: [json, json.item.read], version: '1', max_depth_checks: true } }

        Profile.list: { service: youppers.customer.profile, method: listForUser, jms_serialization_context: { groups: [json, json.profile.list], version: '1', max_depth_checks: true } }
        Profile.create: { service: youppers.customer.profile, method: create, jms_serialization_context: { groups: [json, json.profile.read], version: '1', max_depth_checks: true } }
        Profile.read: { service: youppers.customer.profile, method: read, jms_serialization_context: { groups: [json, json.profile.read], version: '1', max_depth_checks: true } }
        Profile.update: { service: youppers.customer.profile, method: read, jms_serialization_context: { groups: [json, json.profile.read], version: '1', max_depth_checks: true } }
        Profile.delete: { service: youppers.customer.profile, method: read, jms_serialization_context: { groups: [json, json.profile.read], version: '1', max_depth_checks: true } }

        Store.list: { service: youppers.dealer.store, method: listForUser, jms_serialization_context: { groups: [json, json.store.list], version: '1', max_depth_checks: true } }
        