_front:
    resource: routing_front.yml
#    prefix: /{_locale}

# redirect routes for the non-locale routes
#front_without_locale:
#    pattern: /
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: root
#        permanent: true # this for 301

_admin:
    resource: routing_admin.yml
#    prefix:   /{_locale}/admin
    prefix:   /admin
    
# redirect routes for the non-locale routes
#admin_without_locale:
#    pattern: /admin
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        permanent: true # this for 301
        
_api:
    resource: routing_api.yml
    prefix:   /api
    