youppers_customer:
    resource: "@YouppersCustomerBundle/Controller/"
    type:     annotation
    prefix:   /

youppers_dealer:
    resource: "@YouppersDealerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_admin_intl:
    resource: routing_admin.yml
    prefix:   /{_locale}/admin

scraper:
    resource: "@YouppersScraperBundle/Controller/"
    type:     annotation

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcodegenerator
        
#_admin:
#    resource: routing_admin.yml
#    prefix:   /admin

#_api:
#    resource: routing_api.yml
#    prefix:   /api
    